import { useMemo, useState } from "react";
import { View, Text, Pressable, ScrollView, StyleSheet } from "react-native";
import { fetchQuiz, QuizChoice, QuizPayload } from "../../lib/quizClient";
import { useProgress } from "../../lib/progressContext";

const PASS_SCORE = 4; // out of 5

export default function LearnScreen() {

  const [loading, setLoading] = useState(false);
  const [quiz, setQuiz] = useState<QuizPayload | null>(null);
  const [answers, setAnswers] = useState<Record<string, QuizChoice | null>>({});
  const [submitted, setSubmitted] = useState(false);
  const [unlocked, setUnlocked] = useState(false);
  const { setCycleBadgeUnlockedLive, addPoints } = useProgress();

  const score = useMemo(() => {
    if (!quiz || !submitted) return null;
    let s = 0;
    for (const q of quiz.questions) {
      if (answers[q.id] && answers[q.id] === q.answer) s += 1;
    }
    return s;
  }, [quiz, submitted, answers]);

  async function startQuiz() {
    setLoading(true);
    setSubmitted(false);
    setUnlocked(false);

    try {
      const q = await fetchQuiz({
        topic: "Cycle Phases + Symptoms + Nutrition Basics",
        level: "beginner",
        numQuestions: 5,
      });

      setQuiz(q);

      // init answer map
      const init: Record<string, QuizChoice | null> = {};
      q.questions.forEach((qq) => (init[qq.id] = null));
      setAnswers(init);
    } finally {
      setLoading(false);
    }
  }

  function choose(questionId: string, choice: QuizChoice) {
    if (submitted) return;
    setAnswers((prev) => ({ ...prev, [questionId]: choice }));
  }

  async function submit() {
    if (!quiz) return;

    // ensure all answered
    const anyBlank = quiz.questions.some((q) => !answers[q.id]);
    if (anyBlank) return;

    // compute score
    let s = 0;
    for (const q of quiz.questions) {
      if (answers[q.id] === q.answer) s += 1;
    }

    setSubmitted(true);

    // unlock badge if pass
    if (s >= PASS_SCORE) {
      setUnlocked(true);
      await setCycleBadgeUnlockedLive(true);
      
      await addPoints(100);
    }
  }

  function reset() {
    setQuiz(null);
    setSubmitted(false);
    setUnlocked(false);
    setAnswers({});
  }

  return (
    <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
      {!quiz ? (
        <View style={styles.panel}>
          <View style={styles.panelBody}>
            <View style={styles.infoCard}>
              <Text style={styles.infoTitle}>You’re at Level 1</Text>
              <Text style={styles.infoText}>Learn the basics, take a short quiz, unlock your badge.</Text>
            </View>

            <View style={styles.infoCard}>
              <Text style={styles.infoTitle}>Take a Quiz</Text>
              <Text style={styles.infoText}>
                5-question quiz generated by Gemini based on cycle phases, common symptoms, and nutrition basics.
              </Text>
            </View>

            <Pressable
              onPress={startQuiz}
              disabled={loading}
              style={[styles.startBtn, loading && { backgroundColor: "#D38AA8" }]}
            >
              <Text style={styles.startBtnText}>{loading ? "Loading…" : "Start Quiz"}</Text>
            </Pressable>

            {unlocked ? (
              <View style={styles.badgeCallout}>
                <Text style={styles.badgeCalloutTitle}>Badge unlocked</Text>
                <Text style={styles.badgeCalloutText}>Go to Badges to mint Cycle Literacy Level 1.</Text>
              </View>
            ) : null}
          </View>
        </View>
      ) : (
        <View style={{ gap: 12 }}>
          <View style={{ backgroundColor: "#FFF", borderRadius: 16, padding: 16, gap: 8, borderWidth: 1, borderColor: "#F2B7CC" }}>
            <Text style={{ color: "#333", fontWeight: "800" }}>{quiz.topic}</Text>
            <Text style={{ color: "#555" }}>Choose the best answer for each question.</Text>

            {quiz.questions.map((q, idx) => (
              <View key={q.id} style={{ marginTop: 10, gap: 8 }}>
                <Text style={{ color: "#333", fontWeight: "800" }}>
                  {idx + 1}. {q.question}
                </Text>

                {(["A", "B", "C", "D"] as QuizChoice[]).map((ch) => {
                  const selected = answers[q.id] === ch;
                  const correct = submitted && q.answer === ch;
                  const wrongSelected = submitted && selected && q.answer !== ch;

                  return (
                    <Pressable
                      key={ch}
                      onPress={() => choose(q.id, ch)}
                      style={{
                        paddingVertical: 10,
                        paddingHorizontal: 12,
                        borderRadius: 14,
                        backgroundColor: selected ? "#FDECEF" : "#FFFFFF",
                        borderWidth: 1,
                        borderColor: correct ? "#2E7D32" : wrongSelected ? "#C62828" : "#F48FB1",
                        opacity: submitted ? 0.9 : 1,
                      }}
                    >
                      <Text style={{ color: "#333" }}>
                        {ch}. {q.choices[ch]}
                      </Text>
                    </Pressable>
                  );
                })}

                {submitted && (
                  <Text style={{ color: "#555" }}>
                    Explanation: {q.explanation}
                  </Text>
                )}
              </View>
            ))}

            {!submitted ? (
              <Pressable
                onPress={submit}
                style={{
                  marginTop: 14,
                  backgroundColor: "#D81B60",
                  borderRadius: 999,
                  paddingVertical: 12,
                  alignItems: "center",
                }}
              >
                <Text style={{ color: "#FFF", fontWeight: "700" }}>Submit</Text>
              </Pressable>
            ) : (
              <View style={{ marginTop: 14, gap: 10 }}>
                <View
                  style={{
                    backgroundColor: "#FDECEF",
                    borderRadius: 16,
                    padding: 12,
                    borderWidth: 1,
                    borderColor: "#F48FB1",
                  }}
                >
                  <Text style={{ color: "#333", fontWeight: "800" }}>
                    Score: {score}/5
                  </Text>
                  <Text style={{ color: "#333" }}>
                    {score !== null && score >= PASS_SCORE
                      ? "You passed and unlocked the Cycle Literacy badge."
                      : "You didn’t pass yet. Try again!"}
                  </Text>
                </View>

                <Pressable
                  onPress={reset}
                  style={{
                    backgroundColor: "#FDECEF",
                    borderRadius: 999,
                    paddingVertical: 12,
                    alignItems: "center",
                  }}
                >
                  <Text style={{ color: "#333", fontWeight: "700" }}>Back</Text>
                </Pressable>
              </View>
            )}
          </View>
        </View>
      )}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FDECEF",
  },
  content: {
    padding: 16,
    paddingBottom: 110,
  },
  panel: {
    marginTop: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#F2B7CC",
  },
  panelBody: {
    gap: 12,
    padding: 16,
  },
  infoCard: {
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#F2B7CC",
    borderRadius: 12,
    padding: 12,
    gap: 6,
  },
  infoTitle: {
    color: "#2D2230",
    fontFamily: "Onest-Bold",
    fontSize: 22,
  },
  infoText: {
    color: "#2D2230",
    fontFamily: "Onest",
    fontSize: 16,
    lineHeight: 22,
  },
  startBtn: {
    backgroundColor: "#BA5D84",
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
  },
  startBtnText: {
    color: "#FFF",
    fontFamily: "Onest-Bold",
    fontSize: 20,
  },
  badgeCallout: {
    backgroundColor: "#FDECEF",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#F48FB1",
  },
  badgeCalloutTitle: {
    color: "#333",
    fontFamily: "Onest-Bold",
    fontSize: 18,
  },
  badgeCalloutText: {
    color: "#333",
    fontFamily: "Onest",
    fontSize: 14,
  },
});
