import { useMemo, useState } from "react";
import { View, Text, Pressable, ScrollView, StyleSheet } from "react-native";
import { fetchQuiz, QuizChoice, QuizPayload } from "../../lib/quizClient";
import { useProgress } from "../../lib/progressContext";

const PASS_SCORE = 4; // out of 5

export default function LearnScreen() {
  const [loading, setLoading] = useState(false);
  const [quiz, setQuiz] = useState<QuizPayload | null>(null);
  const [answers, setAnswers] = useState<Record<string, QuizChoice | null>>({});
  const [submitted, setSubmitted] = useState(false);
  const [unlocked, setUnlocked] = useState(false);
  const { setCycleBadgeUnlockedLive, addPoints } = useProgress();

  const score = useMemo(() => {
    if (!quiz || !submitted) return null;
    let s = 0;
    for (const q of quiz.questions) {
      if (answers[q.id] && answers[q.id] === q.answer) s += 1;
    }
    return s;
  }, [quiz, submitted, answers]);

  async function startQuiz() {
    setLoading(true);
    setSubmitted(false);
    setUnlocked(false);
    try {
      const q = await fetchQuiz({
        topic: "Cycle Phases + Symptoms + Nutrition Basics",
        level: "beginner",
        numQuestions: 5,
      });
      setQuiz(q);
      const init: Record<string, QuizChoice | null> = {};
      q.questions.forEach((qq) => (init[qq.id] = null));
      setAnswers(init);
    } finally {
      setLoading(false);
    }
  }

  function choose(questionId: string, choice: QuizChoice) {
    if (submitted) return;
    setAnswers((prev) => ({ ...prev, [questionId]: choice }));
  }

  async function submit() {
    if (!quiz) return;
    const anyBlank = quiz.questions.some((q) => !answers[q.id]);
    if (anyBlank) return;

    let s = 0;
    for (const q of quiz.questions) {
      if (answers[q.id] === q.answer) s += 1;
    }
    setSubmitted(true);

    if (s >= PASS_SCORE) {
      setUnlocked(true);
      await setCycleBadgeUnlockedLive(true);
      
      await addPoints(100);
    }
  }

  function reset() {
    setQuiz(null);
    setSubmitted(false);
    setUnlocked(false);
    setAnswers({});
  }

  return (
    <ScrollView contentContainerStyle={styles.content}>
      {/* Intro Card */}
      <View style={styles.card}>
        <Text style={styles.cardTitle}>Cycle Literacy</Text>
        <Text style={styles.cardText}>
          Learn the basics, take a short quiz, unlock your badge.
        </Text>
      </View>

      {!quiz ? (
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Level 1</Text>
          <Text style={styles.cardText}>
            5-question quiz generated by Gemini based on cycle phases, common symptoms, and nutrition basics.
          </Text>

          <Pressable
            onPress={startQuiz}
            disabled={loading}
            style={[styles.primaryBtn, loading && { backgroundColor: "#F48FB1" }]}
          >
            <Text style={styles.primaryText}>
              {loading ? "Loading…" : "Start Quiz"}
            </Text>
          </Pressable>

          {unlocked && (
            <View style={styles.unlockedCard}>
              <Text style={styles.cardTitle}>Badge unlocked</Text>
              <Text style={styles.cardText}>
                Go to Badges to mint Cycle Literacy Level 1.
              </Text>
            </View>
          )}
        </View>
      ) : (
        <View style={{ gap: 12 }}>
          <View style={styles.card}>
            <Text style={styles.cardTitle}>{quiz.topic}</Text>
            <Text style={styles.cardText}>Choose the best answer for each question.</Text>

            {quiz.questions.map((q, idx) => (
              <View key={q.id} style={{ marginTop: 10, gap: 8 }}>
                <Text style={styles.questionText}>
                  {idx + 1}. {q.question}
                </Text>

                {(["A", "B", "C", "D"] as QuizChoice[]).map((ch) => {
                  const selected = answers[q.id] === ch;
                  const correct = submitted && q.answer === ch;
                  const wrongSelected = submitted && selected && q.answer !== ch;

                  return (
                    <Pressable
                      key={ch}
                      onPress={() => choose(q.id, ch)}
                      style={[
                        styles.choiceBtn,
                        selected && { backgroundColor: "#FDECEF" },
                        correct && { borderColor: "#2E7D32" },
                        wrongSelected && { borderColor: "#C62828" },
                      ]}
                    >
                      <Text style={styles.choiceText}>
                        {ch}. {q.choices[ch]}
                      </Text>
                    </Pressable>
                  );
                })}

                {submitted && <Text style={styles.cardText}>Explanation: {q.explanation}</Text>}
              </View>
            ))}

            {!submitted ? (
              <Pressable onPress={submit} style={styles.primaryBtn}>
                <Text style={styles.primaryText}>Submit</Text>
              </Pressable>
            ) : (
              <View style={{ marginTop: 14, gap: 10 }}>
                <View style={styles.unlockedCard}>
                  <Text style={styles.cardTitle}>Score: {score}/5</Text>
                  <Text style={styles.cardText}>
                    {score !== null && score >= PASS_SCORE
                      ? "You passed and unlocked the Cycle Literacy badge."
                      : "You didn’t pass yet. Try again!"}
                  </Text>
                </View>

                <Pressable onPress={reset} style={[styles.primaryBtn, { backgroundColor: "#FDECEF" }]}>
                  <Text style={[styles.primaryText, { color: "#333" }]}>Back</Text>
                </Pressable>
              </View>
            )}
          </View>
        </View>
      )}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  content: {
    flexGrow: 1,
    padding: 25,
    paddingTop: 40,
    paddingBottom: 80, // ensures content stops above tab bar
    gap: 18,
    backgroundColor: "#fff",
  },
  card: {
    gap: 10,
    padding: 16,
    borderWidth: 1,
    borderColor: "#ea9ab2",
    borderRadius: 10,
    backgroundColor: "#fff",
    shadowColor: "#ea9ab2",
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 10,
  },
  cardTitle: {
    fontFamily: "Onest-Bold",
    fontSize: 24,
    color: "#250921",
  },
  cardText: {
    fontFamily: "Onest",
    fontSize: 16,
    color: "#250921",
  },
  questionText: {
    fontFamily: "Onest-Bold",
    fontSize: 16,
    color: "#250921",
  },
  choiceBtn: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#F48FB1",
  },
  choiceText: {
    color: "#333",
  },
  primaryBtn: {
    backgroundColor: "#D81B60",
    borderRadius: 999,
    paddingVertical: 12,
    alignItems: "center",
    marginTop: 10,
  },
  primaryText: {
    color: "#FFF",
    fontWeight: "700",
  },
  unlockedCard: {
    backgroundColor: "#FDECEF",
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: "#F48FB1",
  },
});